# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1071, 628)
        Form.setStyleSheet("QWidget {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                      stop:0 #eaf6ff, stop:1 #cfe8ff);\n"
"}")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 200, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #0a2b55;")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(110, 290, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #0a2b55;")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.txtMaSV = QtWidgets.QLineEdit(Form)
        self.txtMaSV.setGeometry(QtCore.QRect(320, 200, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtMaSV.setFont(font)
        self.txtMaSV.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txtMaSV.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #a0cfff;\n"
"    border-radius: 6px;\n"
"    padding: 5px;\n"
"    font-size: 12pt;\n"
"}")
        self.txtMaSV.setText("")
        self.txtMaSV.setObjectName("txtMaSV")
        self.txtHoTen = QtWidgets.QLineEdit(Form)
        self.txtHoTen.setGeometry(QtCore.QRect(320, 290, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtHoTen.setFont(font)
        self.txtHoTen.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #a0cfff;\n"
"    border-radius: 6px;\n"
"    padding: 5px;\n"
"    font-size: 12pt;\n"
"}")
        self.txtHoTen.setObjectName("txtHoTen")
        self.btnLayAnh = QtWidgets.QPushButton(Form)
        self.btnLayAnh.setGeometry(QtCore.QRect(380, 460, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnLayAnh.setFont(font)
        self.btnLayAnh.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 #dceeff, stop:1 #a3cfff);\n"
"    border: 1px solid #87bfff;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    color: #0a2b55;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c0e0ff;\n"
"}")
        self.btnLayAnh.setObjectName("btnLayAnh")
        self.btnCapNhat = QtWidgets.QPushButton(Form)
        self.btnCapNhat.setGeometry(QtCore.QRect(810, 160, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnCapNhat.setFont(font)
        self.btnCapNhat.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 #dceeff, stop:1 #a3cfff);\n"
"    border: 1px solid #87bfff;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    color: #0a2b55;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c0e0ff;\n"
"}")
        self.btnCapNhat.setObjectName("btnCapNhat")
        self.btnNhanDang = QtWidgets.QPushButton(Form)
        self.btnNhanDang.setGeometry(QtCore.QRect(810, 300, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnNhanDang.setFont(font)
        self.btnNhanDang.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 #dceeff, stop:1 #a3cfff);\n"
"    border: 1px solid #87bfff;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    color: #0a2b55;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c0e0ff;\n"
"}")
        self.btnNhanDang.setObjectName("btnNhanDang")
        self.btnThuKhuonMat_Anh = QtWidgets.QPushButton(Form)
        self.btnThuKhuonMat_Anh.setGeometry(QtCore.QRect(10, 460, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnThuKhuonMat_Anh.setFont(font)
        self.btnThuKhuonMat_Anh.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 #dceeff, stop:1 #a3cfff);\n"
"    border: 1px solid #87bfff;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    color: #0a2b55;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c0e0ff;\n"
"}")
        self.btnThuKhuonMat_Anh.setObjectName("btnThuKhuonMat_Anh")
        self.btnNhanDienKhuonMat_AnhVideo = QtWidgets.QPushButton(Form)
        self.btnNhanDienKhuonMat_AnhVideo.setGeometry(QtCore.QRect(560, 460, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnNhanDienKhuonMat_AnhVideo.setFont(font)
        self.btnNhanDienKhuonMat_AnhVideo.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 #dceeff, stop:1 #a3cfff);\n"
"    border: 1px solid #87bfff;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    color: #0a2b55;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c0e0ff;\n"
"}")
        self.btnNhanDienKhuonMat_AnhVideo.setObjectName("btnNhanDienKhuonMat_AnhVideo")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(260, 40, 581, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #0a2b55;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Nhận diện khuôn mặt"))
        self.label_2.setText(_translate("Form", "Mã sinh viên"))
        self.label_3.setText(_translate("Form", "Họ và tên"))
        self.btnLayAnh.setText(_translate("Form", "Lấy Ảnh"))
        self.btnCapNhat.setText(_translate("Form", "Cập Nhật"))
        self.btnNhanDang.setText(_translate("Form", "Nhận Diện"))
        self.btnThuKhuonMat_Anh.setText(_translate("Form", "Thu Khuôn Mặt Bằng Ảnh"))
        self.btnNhanDienKhuonMat_AnhVideo.setText(_translate("Form", "Nhận Diện Khuôn Mặt Bằng Ảnh/Video"))
        self.label_4.setText(_translate("Form", "NHẬN DIỆN KHUÔN MẶT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
